Use Tutorias
go
--Agregar Estudiantes a la base de Datos

insert into Estudiante values ('HAYDER','AUCCAISE RONCO','2021-I','182896','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2018')
insert into Estudiante values ('ABEL ENRIQUE','BELLIDO ARMUTO','2021-I','204318','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2020')
insert into Estudiante values ('GEORGE SANTIAGO','CASTELLANOS AMANQUI','2021-I','151832','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2015')
insert into Estudiante values ('LUIS FERNANDO','CONDORI-LACUTA-','2021-I','	204319','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2020')
insert into Estudiante values ('EMERSON','CORDOVA-CCOPA','2021-I','184195','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2018')
insert into Estudiante values ('JANNIRA ALISON','FARFAN LUNA','2021-I','204796','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2020')
insert into Estudiante values ('JHONATAN ALEXANDER','GARCIA ROMERO','2021-I','204320','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','204320')
insert into Estudiante values ('DANY DARWIN','HUACANI DE LA CRUZ','2021-I','081561','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2008')
insert into Estudiante values ('ANGGIE ANTUANE','HUAMAN MORALES','2021-I','160696','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2016')
insert into Estudiante values ('ASUMY MARICELY','JALLO-PACCAYA','2021-I','204799','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2020')
insert into Estudiante values ('OLIVER STIVEN','VELASQUEZ-QUISPE','2021-I','174457','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2017')
insert into Estudiante values ('MAX ALEX','SONCCO-LUQUE','2021-I','194892','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2019')
insert into Estudiante values ('204321	NIETO-BARRIENTOS-YISHAR PIERO','JALLO-PACCAYA-Y','2021-I','204799','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2020')
insert into Estudiante values ('JOSEPH ODE','ESPIRILLA MACHACA','2021-I','145004','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2014')
insert into Estudiante values ('GEORGE SANTIAGO','CASTELLANOS-AMANQUI','2021-I','151832','INGENIERIA INFORMATICA Y DE SISTEMAS','IN','2015')

insert into Estudiante values ('EDSON','ASTETE-VELASQUE','2021-I','124944','MEDICINA HUMANA','MH','2012')
insert into Estudiante values ('MARI LUZ','AUCCAPURE SERRANO','2021-I','144260','MEDICINA HUMANA','MH','2014')
insert into Estudiante values ('GUIDO RODOLFO','BERRIOS ALOSILLA','2021-I','201256','MEDICINA HUMANA','MH','2020')
insert into Estudiante values ('YULIANA EUNISE','BUSTAMANTE SANCHEZ','2021-I','194689','MEDICINA HUMANA','MH','2019')
insert into Estudiante values ('KELLY DAYSI','HUAMAN HUILLCA','2021-I','154937','MEDICINA HUMANA','MH','2015')
insert into Estudiante values ('LUCERO MILAGROS','HUAMANI ESTRADA','2021-I','151481','MEDICINA HUMANA','MH','2015')
insert into Estudiante values ('JURGUEN ANDRE','LUNA TAPIA','2021-I','200847','MEDICINA HUMANA','MH','2020')
insert into Estudiante values ('NAYHELY ALEXANDRA','MAMANI HUARAYA','2021-I','201257','MEDICINA HUMANA','MH','2020')
insert into Estudiante values ('YOSELIN ESTHER','MEZA VARGAS','2021-I','193681','MEDICINA HUMANA','MH','2019')
insert into Estudiante values ('BRAYAN LUIS','MUÑOZ AREVALO','2021-I','193682','MEDICINA HUMANA','MH','2019')
insert into Estudiante values ('DANNI VICENTE','SUCARI QUISPE','2021-I','183339','MEDICINA HUMANA','MH','2018')
insert into Estudiante values ('NAOMI VICTORIA','VARGAS ORTIZ','2021-I','194728','MEDICINA HUMANA','MH','2019')
go
--Agregar docentes con datos reales
insert into Docente values ('D0001','Abdon','Ribas Puga','Licenciado en Fisico Matematicas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0002','Ana Rocio','Cardenas Maita','Magister en Ciencias en Sistemas de Informacion','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0003','Dennis Ivan','Candia Oviedo','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0004','Doris Sabina','Aguirre Carbajal','Maestro en Ciencias: Ing de Sistemas con mencion en Ing de Software','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0005','Edwin','Carrasco Poblete','Magister con Mencion en Ingenieria','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')

insert into Docente values ('D0006','Efraina Gladys','Cutipa Arapa','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0007','Emilio','Palomino Olivera','Magister con Mencion en Ingenieria','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0008','Enrique','Gamarra Saldivar','Magister en Ciencias con Mencion en Informatica','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0009','Esther Cristina','Pacheco Vasquez','Licenciada en Fisico Matematicas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0010','Guzman','Ticona Pari','Ingeniero Quimico','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')

insert into Docente values ('D0011','Harley','Vera Olivera','Magister en Informatica','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0012','Henry Samuel','Dueñas De La Cruz','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0013','Hernan','Castañeda Chirinos','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0014','Hernan','Nina Hanco','Maestro en Administracion','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0015','Ivan Cesar','Medrano Valencia','Ingeniero Quimico','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')

insert into Docente values ('D0016','Javier Arturo','Rozas Huacho','Magister en Ciencias con Mencion en Informatica','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0017','Javier David','Chavez Centeno','Magister Scientiae en Informatica','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0018','Jose Mauro','Pillco Quispe','Licenciado en Fisico Matematicas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0019','Julio Cesar','Carbajal Luna','Magister en Ciencias con Mencion en Informatica','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0020','Karelia','Medina Miranda','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')

insert into Docente values ('D0021','Lauro','Enciso Rodas','Doctor en Ingenieria de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0022','Lino Aquiles','Baca Cardenas','Ingeniero de Minas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0023','Lino Prisciliano','Flores Pacheco','Magister en Informatica','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0024','Luis Alvaro','Monzon Condori','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0025','Luis Beltran','Palma Ttito','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')

insert into Docente values ('D0025','Manuel Aurelio','Peñaloza Figueroa','Ingeniero de Telecomunicaciones','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0026','Maritza Katherine','Irpanocca Cusimayta','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0027','Nila Zonia','Acurio Usca','Magister en Ciencias con Mencion en Informatica','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0028','Robert Wilbert','Alzamora Paredes','Master en Ingenieria Computacional y Sistemas Inteligentes','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0029','Rony','Villafuerte Serna','Maestro en Ingenieria Computacional y Sistemas Inteligentes','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')

insert into Docente values ('D0030','Vanesa Maribel','Choque Soto','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0031','Waldo Elio','Ibarra Zambrano','Maestro en Ciencias con Mencion en Informatica','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
insert into Docente values ('D0032','Waldo','Villa Rodriguez','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0033','Willian','Zamalloa Paro','Ingeniero Informatico y de Sistemas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Contratado')
insert into Docente values ('D0034','Yeshica Isela','Ormeño Ayala','Master en Tecnologias Informaticas Avanzadas','Facultad de Ingenieria Electrica, Electronica, Informatica y Mecanica','Ingenieria Informatica y de Sistemas','Nombrado')
go

--ingresar datos Tutoria
insert into Tutoria values(5, 'LUNES 06:00 PM - 08:00 PM')
insert into Tutoria values(7, 'JUEVES 04:00 PM - 06:00 PM')
insert into Tutoria values(10, 'MIERCOLES 01:00 PM - 03:00 PM')
insert into Tutoria values(15, 'SABADO 09:00 AM - 11:00 AM')
insert into Tutoria values(16, 'LUNES 03:00 PM - 05:00 PM')
insert into Tutoria values(21, 'MARTES 04:00 PM - 06:00 PM')
go
--Ingresar Datos Registro tutoria
insert into Registro values(1,1)
insert into Registro values(1,2)
insert into Registro values(1,3)
insert into Registro values(1,4)
insert into Registro values(1,5)
insert into Registro values(2,6)
insert into Registro values(2,7)
insert into Registro values(2,8)
insert into Registro values(2,9)
insert into Registro values(2,10)
insert into Registro values(3,11)
insert into Registro values(3,12)
insert into Registro values(3,13)
insert into Registro values(3,14)
insert into Registro values(3,15)
insert into Registro values(4,16)
insert into Registro values(4,17)
insert into Registro values(4,18)
insert into Registro values(4,19)
insert into Registro values(4,20)
insert into Registro values(5,21)
insert into Registro values(5,22)
insert into Registro values(5,23)
insert into Registro values(5,24)
insert into Registro values(5,25)
insert into Registro values(6,26)
insert into Registro values(6,27)
--insert into Registro values(6,28)
--insert into Registro values(6,29)
--insert into Registro values(6,30)
go
--Ingresar Registro de ficha
insert into RegistroFicha values(1,1,'916000366','AV. REPUBLICA DE PANAMA Nº 4825','1@unsaac.edu.pe','JUAN AUCCAISE ','906411393','2021-03-01','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(1,2,'911574993','ALBERTO BRICEÑO Nº 217','2@unsaac.edu.pe','MARIO BELLIDO','922627389','2021-03-02','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(1,3,'912944402','AV. GENERAL DIEZ CANSECONº 527 - AREQUIPA','3@unsaac.edu.pe','JUANA CASTELLANOS','986709284','2021-03-03','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(1,4,'969609532','AV. LA MARINA N° 340, MARGEN IZQUIERDA DEL RIO AMAZONAS','4@unsaac.edu.pe','CARLOS CONDORI','933636737','2021-03-04','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(1,5,'946773342','SECHURA A 110 KM. AL SUR DE PIURA - AREA DE PLANTA CONCENTRADORA, OFICINAS Y COMPLEMENTARIOS DE LA MINA','5@unsaac.edu.pe','MARIO CCOPA','972581441','2021-03-05','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(2,6,'985423133','AV. VICTOR MALASQUEZ KM 5 LOTE 10 SECTOR 24 DE JUNIO','6@unsaac.edu.pe','YUREMA FARFAN','909937497','2021-03-06','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(2,7,'982808273','AV. EL EJERCITO S/N CUADRA 11 - CUARTEL LOS CABITOS','7@unsaac.edu.pe','ALONDRA GARCIA','962827995','2021-03-07','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(2,8,'991210968','JIRON ILO 450 ESQ. CON JIRON CHOTA 998','8@unsaac.edu.pe','LUCIO DE LA CRUZ','931725496','2021-03-08','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(2,9,'939742194','KM. 95 DE LA CARRETERA CENTRAL','9@unsaac.edu.pe','SONIA MORALES','978482915','2021-03-09','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(2,10,'962199795','AV. FORTUNATO CHIRICHINGNO S/N EL CHIPE','10@unsaac.edu.pe','EUGENIO JALLO','915432325','2021-03-10','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(3,11,'924969802','AV. EVITAMIENTO Nº 242 - PARQUE INDUSTRIAL','11@unsaac.edu.pe','FRED VELASQUEZ','977020676','2021-03-11','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(3,12,'917201475','CARRETERA CENTRAL KM. 8,500 DISTRITO STA. CLARA','12@unsaac.edu.pe','JOSE SONCCO','916217453','2021-03-12','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(3,13,'955538187','AV. PRODUCCIÓN NACIONAL 188','13@unsaac.edu.pe','MIGUEL BARRIENTOS','956698835','2021-03-13','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(3,14,'912953693','JR. LOS HORNOS N° 353 - URB. INFANTAS','14@unsaac.edu.pe','FRANCO ESPIRILLA','991377512','2021-03-14','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(3,15,'980466029','JR. ALONSO DE MOLINA N° 193. EX ZONA INDUSTRIAL','15@unsaac.edu.pe','MARIA CASTELLANOS','973768689','2021-03-15','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(4,16,'985888531','PANAMERICANA SUR S/N, KM 3 + 751 VIA FERREA MATARANI – AREQUIPA','16@unsaac.edu.pe','PABLO ASTETE','963267139','2021-03-16','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(4,17,'927913633','KM. 14.8 DE LA CARRETERA CENTRAL, GLORIA ALTA (MINERA LA GLORIA)','17@unsaac.edu.pe','RUFINO AUCCAPURE','952379021','2021-03-17','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(4,18,'992132959','SECTOR POBLADO YAURILLA S/N','18@unsaac.edu.pe','VICTOR BERRIOS','967238612','2021-03-18','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(4,19,'929822932','CALLE DELTA 185 URB.PARQUE INTERNA.DE LA INDUSTR.Y COMERC.','19@unsaac.edu.pe','MARIA BERRIOS','901560473','2021-03-19','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(4,20,'951315821','AV. LOS LIBERTADORES KM. 1.50','20@unsaac.edu.pe','ERICK BUSTAMANTE','985937997','2021-03-20','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(5,21,'954105618','AV. UNIV. S/N, GRP. 1, AA.HH. EDILBERTO RAMOS','21@unsaac.edu.pe','INDIRA HUILLCA','990847112','2021-03-21','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(5,22,'962314146','CALLE RAMON CASTILLA, URB. LURIN LOTE 6, FUNDO SALINAS','22@unsaac.edu.pe','DENIS HUAMAN','957819746','2021-03-22','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(5,23,'954400921','CALLE INCA ROCA Y MANCO III MZ.C15 LT.2 AA.HH.LEONCIO PRADO','23@unsaac.edu.pe','JAVIER HUAMANI','990584577','2021-03-23','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(5,24,'907131525','AV. NICOLAS ARRIOLA N° 3192','24@unsaac.edu.pe','ENZO LUNA','927690099','2021-03-24','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(5,25,'924465278','AV. SANTA JOSEFINA ALT. KM. 30.1 PANAMERICANA NORTE','25@unsaac.edu.pe','VLADI HUARAYA','906145016','2021-03-25','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(6,26,'924562816','ZONA INDUSTRIAL S/N TALARA ALTA','26@unsaac.edu.pe','ABENCIA MEZA','936036471','2021-03-26','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
insert into RegistroFicha values(6,27,'946509532','PREDIO ERIAZO UBICADO ENTRE LOS SECTORES LA CANO Y SAN JOSE, ALTURA DE LA CARRETERA PANAMERICANA SUR KM. 981.7 PLANTA DE SUPERFAM Y PLANTA DE EMULSION','27@unsaac.edu.pe','HECTOR MUÑOZ','934354141','2021-03-27','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
--insert into RegistroFicha values(6,28,'991707983','JR. JORGE CHAVEZ N° 803','28@unsaac.edu.pe','TOÑO VARGAS','951424294','2021-03-28','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
--insert into RegistroFicha values(6,29,'946130060','CARRETERA SECHURA - BAYOVAR KM 20 + 639','29@unsaac.edu.pe','FRED MENA','925061955','2021-03-29','ACADÉMICA','TgBPACAAUABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
--insert into RegistroFicha values(6,30,'950574953','PREDIO LA ESMERALDA U.C. 15436 A, AV. AEROPUERTO S/N','30@unsaac.edu.pe','RUFINA QUISPE','985757586','2021-03-30','ACADÉMICA','UABSAEUAUwBFAE4AVABBACAAUABSAE8AQgBMAEUATQBBAFMAIABEAEUAIABFAFMAVABVAEQASQBPAA==')
go