version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\PruebasFormulario
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "Tutorias001.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\project\PruebasFormulario\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "Tutorias001.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\Tutorias001.exe
 

  
workflows:
  PruebasFormulario:
    jobs:
      - build